;;; compile-multi-all-the-icons-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from compile-multi-all-the-icons.el

(register-definition-prefixes "compile-multi-all-the-icons" '("compile-multi-all-the-icons-alist"))

;;; End of scraped data

(provide 'compile-multi-all-the-icons-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; compile-multi-all-the-icons-autoloads.el ends here
