;;; bar-cursor-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bar-cursor.el

(defvar bar-cursor-mode nil "\
Non-nil if bar-Cursor mode is enabled.
See the `bar-cursor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `bar-cursor-mode'.")
(custom-autoload 'bar-cursor-mode "bar-cursor" nil)
(autoload 'bar-cursor-mode "bar-cursor" "\
Toggle use of 'bar-cursor-mode'.

This global minor mode changes cursor to a bar cursor in insert
mode, and a block cursor in overwrite mode.

This is a global minor mode.  If called interactively, toggle the
`bar-Cursor mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='bar-cursor-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "bar-cursor" '("bar-cursor-set-cursor"))

;;; End of scraped data

(provide 'bar-cursor-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bar-cursor-autoloads.el ends here
